CREATE TABLE EXPENSE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER,
    AMOUNT DECIMAL(10,2), -- Or DECIMAL(10, 2) if you want to suggest precision and scale
    CATEGORY TEXT,
    DATE TEXT,
    NOTES TEXT,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);